### ISSUE TITLE
Search behaviour

### ISSUE THREAD

**Issue by david-antos** [oarepo/oarepo-micro-api#7]
Search works for full words, I'd expect it to search for substrings. E.g., a lecture "IPv6 v metropolitní síti Praha1.net" is not found when searching for "Praha", just for "Praha1".

**Comment by mirekys** [comment]
The actual search works by analyzing the query by applying these [filters](https://github.com/oarepo/oarepo-micro-api/pull/8/files#diff-b81dcc98651d49890fcb625ae8f7eb0dL18-R36).

The process is:
- lowercase the query text
- then in #8, I added [word_delimiter](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-word-delimiter-tokenfilter.html), that should split the query on word boundaries (`'Praha1'` will be split into tokens `praha` and `1`)
- `czech_stop` then excludes common czech stopwords (as they are not indexed)
- `czech_stem` will reduce remaining words (tokens) just to a minimal stems of a given words

The resulting tokens for the following query text:
```json
curl --location --request POST 'localhost:9200/records-record-v1.0.0/_analyze?pretty' \
--header 'Content-Type: application/json' \
--data-raw '{
  "analyzer": "default",
  "text":     "IPv6 v metropolitní síti Praha1.net"
}
```
```
{
  "tokens": [
    {
      "token": "ipv",
      "start_offset": 0,
      "end_offset": 3,
      "type": "<ALPHANUM>",
      "position": 0
    },
    {
      "token": "6",
      "start_offset": 3,
      "end_offset": 4,
      "type": "<ALPHANUM>",
      "position": 1
    },
    {
      "token": "metropolitn",
      "start_offset": 7,
      "end_offset": 19,
      "type": "<ALPHANUM>",
      "position": 3
    },
    {
      "token": "sít",
      "start_offset": 20,
      "end_offset": 24,
      "type": "<ALPHANUM>",
      "position": 4
    },
    {
      "token": "prah",
      "start_offset": 25,
      "end_offset": 30,
      "type": "<ALPHANUM>",
      "position": 5
    },
    {
      "token": "1",
      "start_offset": 30,
      "end_offset": 31,
      "type": "<ALPHANUM>",
      "position": 6
    },
    {
      "token": "nt",
      "start_offset": 32,
      "end_offset": 35,
      "type": "<ALPHANUM>",
      "position": 7
    }
  ]
}
```

 are then searched in indexed data (that had undergone the same process) and the search results are then ordered by a score (mainly based on a number of matching tokens).



More info on [Czech search analysis](https://www.zdrojak.cz/clanky/elasticsearch-vyhledavame-cesky/)
